CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=50
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_TIMEOUT=3000000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

CONFIG_ZMK_POINTING=y

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_INVERT=n
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# Debug logging for split connection issues
# CONFIG_ZMK_LOG_LEVEL_DBG=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_POSITION_QUEUE_SIZE=20
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=4000

# Explicitly enable BLE for split
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE=y

CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
